FROM nginx:latest

RUN echo "Start Docker image"

RUN apt-get update -y

RUN apt-get install wget -y

RUN apt install iputils-ping -y

RUN apt install nano -y



COPY nginx_config/nginx.conf /etc/nginx/nginx.conf

# RUN nginx -s reload
RUN echo finish