FROM nginx:latest

RUN echo "Start Docker image"

RUN apt-get update -y

RUN apt-get install wget -y

RUN apt install nano -y

COPY html/faces.html /usr/share/nginx/html/index.html
COPY nginx_config/nginx.conf /etc/nginx/nginx.conf

# RUN nginx -s reload
RUN echo finish