FROM nginx:1.24.0

RUN echo "Start Docker image"

RUN apt-get update -y

RUN apt-get install wget -y

RUN apt install nano -y

RUN mkdir -p /usr/share/nginx/jpeg

COPY html/faces.html /usr/share/nginx/html/index.html
COPY nginx_config/nginx.conf /etc/nginx/nginx.conf
COPY /jpeg/shkaf.jpeg /usr/share/nginx/jpeg/shkaf.jpeg

# RUN nginx -s reload
RUN echo finish